### PR TITLE
PyPI Setup

### PR DESCRIPTION
**Pull request by MiloLurati**
Hello,

I have made some changes to the PyHIP repository in order to add a Python package to PyPI. However, since there is already a package with the name "pyhip" on PyPI, we need to choose a new name for the package. I propose renaming the package to "pyhip-interface", but if you have a different suggestion, we can easily change it in the setup.py file.

Additionally, I have added a global "__version__" variable to the __init__.py file and set the version number to 0.1.0, so that the version number can be accessed programmatically. In addition, I have updated the README file with installation instructions for the new package.

Please let me know if you have any questions or concerns about these changes.

### CODE REVIEW

**Review by jatinx — APPROVED** [review]
LGTM

**Comment by MiloLurati** [comment]
Perfect, thanks for merging! Will you upload the library to PyPI or should I do it?

**Comment by jatinx** [comment]
Can you do it? I am not familiar with the process, will have to look up.

**Comment by MiloLurati** [comment]
Will do!

**Pull request merged**
